server {
    listen 80;
    server_name cx168744.tw1.ru;

    root /usr/share/nginx/html;
    index index.html;

    # Статика: отдаем файлы как есть и кешируем
    location ~* \.(?:css|js|png|jpe?g|gif|ico|svg|woff2?|ttf|eot)$ {
        try_files $uri =404;
        access_log off;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # SPA роутинг: любые несуществующие пути -> index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
